routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('usuario', 'UsuarioCotroller');
Route::resource('butaca', 'ButacaCotroller');
Route::resource('reserva', 'ReservaController');

app/Butaca.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Butaca extends Model
{
    //
    protected $table = 'butaca';
    protected $fillable = ['fila','columna'];
    protected $hidden = ['reservado'];
}

resources/views/butaca/create.blade.php
@extends('layout')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-12 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="card">
				<div class="panel-header">
					<h3 class="card-title">Nuevo Butaca</h3>
				</div>
				<div class="card-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('butaca.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="number" name="fila" id="fila" class="form-control input-sm" placeholder="fila de la butaca">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="number" name="columna" id="columna" class="form-control input-sm" placeholder="columna de la butaca">
									</div>
								</div>
							</div>
							<div class="row">

								<div class="col-xs-12 col-sm-12 col-md-12">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									<a href="{{ route('butaca.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/butaca/edit.blade.php
@extends('layouts.layout')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Edicion de Butaca</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('butaca.update',$butaca->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="number" name="fila" id="fila" class="form-control input-sm" value="{{$butaca->fila}}">
									</div>
								</div>
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="number" name="columna" id="columna" class="form-control input-sm" value="{{$butaca->columna}}">
									</div>
								</div>
							</div>
							<div class="row">

								<div class="col-xs-12 col-sm-12 col-md-12">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									<a href="{{ route('butaca.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/butaca/index.blade.php
@extends('layout')
@section('content')
<div class="row">
  <section class="content">
    <div class="col-lg-12 col-lg-offset-2">
      <div class="card">
        <div class="card-header">
            <div class="pull-left"><h3>Lista Butacas</h3></div>
            <div class="pull-right">
              <div class="btn-group">
                <a href="{{ route('butaca.create') }}" class="btn btn-info" >Añadir Butaca</a>
              </div>
            </div>
        </div>
        <div class="card-body">
          <div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               <th>Fila</th>
               <th>Columna</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($butacas->count())  
              @foreach($butacas as $butaca)  
              <tr>
                <td>{{$butaca->fila}}</td>
                <td>{{$butaca->columna}}</td>
                <td><a class="btn btn-primary btn-lg" href="{{action('ButacaCotroller@edit', $butaca->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('ButacaCotroller@destroy', $butaca->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">

                   <button class="btn btn-danger btn-lg" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
               </tr>
               @endforeach 
               @else
               <tr>
                <td colspan="8"> No hay registro !!</td>
              </tr>
              @endif
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

@endsection